apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-inventory-claim0
  name: postgres-inventory-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}