apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-service
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  strategy: {}
  template:
    metadata:

      labels:
        app: product-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: zeyadaboushanab/product-service:latest
          name: product-service
          resources:
            requests:
              memory: "256Mi"   # Request 256 MiB of memory
              cpu: "250m"       # Request 250 milliCPU (0.25 CPU)
            limits:
              memory: "512Mi"   # Limit to 512 MiB of memory
              cpu: "500m"
      restartPolicy: Always
status: {}