apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
    - name: "8181"
      port: 8181
      targetPort: 8080
  selector:
    app: api-gateway
status:
  loadBalancer: {}
