apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
  name: notification-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 9192
  selector:
    app: notification-service
status:
  loadBalancer: {}